export type Method='dubai'|'umm'|'mwl'|'egypt'|'karachi'|'north';
export type City={id:string;ar:string;en:string;countryAr:string;countryEn:string;code:string;lat:number;lng:number;timezone:string;method:Method};
export const cities:City[]=[
{id:'ae-abu-dhabi',ar:'أبوظبي',en:'Abu Dhabi',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:24.4539,lng:54.3773,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-dubai',ar:'دبي',en:'Dubai',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.2048,lng:55.2708,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-sharjah',ar:'الشارقة',en:'Sharjah',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.3463,lng:55.4209,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-ajman',ar:'عجمان',en:'Ajman',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.4052,lng:55.5136,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-uaq',ar:'أم القيوين',en:'Umm Al Quwain',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.5647,lng:55.5552,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-rak',ar:'رأس الخيمة',en:'Ras Al Khaimah',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.8007,lng:55.9762,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-fujairah',ar:'الفجيرة',en:'Fujairah',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:25.1288,lng:56.3265,timezone:'Asia/Dubai',method:'dubai'},
{id:'ae-al-ain',ar:'العين',en:'Al Ain',countryAr:'الإمارات',countryEn:'UAE',code:'AE',lat:24.1302,lng:55.8023,timezone:'Asia/Dubai',method:'dubai'},
{id:'sa-makkah',ar:'مكة المكرمة',en:'Makkah',countryAr:'السعودية',countryEn:'Saudi Arabia',code:'SA',lat:21.3891,lng:39.8579,timezone:'Asia/Riyadh',method:'umm'},
{id:'sa-madinah',ar:'المدينة المنورة',en:'Madinah',countryAr:'السعودية',countryEn:'Saudi Arabia',code:'SA',lat:24.5247,lng:39.5692,timezone:'Asia/Riyadh',method:'umm'},
{id:'sa-riyadh',ar:'الرياض',en:'Riyadh',countryAr:'السعودية',countryEn:'Saudi Arabia',code:'SA',lat:24.7136,lng:46.6753,timezone:'Asia/Riyadh',method:'umm'},
{id:'sa-jeddah',ar:'جدة',en:'Jeddah',countryAr:'السعودية',countryEn:'Saudi Arabia',code:'SA',lat:21.4858,lng:39.1925,timezone:'Asia/Riyadh',method:'umm'},
{id:'qa-doha',ar:'الدوحة',en:'Doha',countryAr:'قطر',countryEn:'Qatar',code:'QA',lat:25.2854,lng:51.531,timezone:'Asia/Qatar',method:'umm'},
{id:'kw-kuwait',ar:'مدينة الكويت',en:'Kuwait City',countryAr:'الكويت',countryEn:'Kuwait',code:'KW',lat:29.3759,lng:47.9774,timezone:'Asia/Kuwait',method:'umm'},
{id:'bh-manama',ar:'المنامة',en:'Manama',countryAr:'البحرين',countryEn:'Bahrain',code:'BH',lat:26.2235,lng:50.5876,timezone:'Asia/Bahrain',method:'umm'},
{id:'om-muscat',ar:'مسقط',en:'Muscat',countryAr:'عمان',countryEn:'Oman',code:'OM',lat:23.588,lng:58.3829,timezone:'Asia/Muscat',method:'umm'},
{id:'eg-cairo',ar:'القاهرة',en:'Cairo',countryAr:'مصر',countryEn:'Egypt',code:'EG',lat:30.0444,lng:31.2357,timezone:'Africa/Cairo',method:'egypt'},
{id:'eg-alex',ar:'الإسكندرية',en:'Alexandria',countryAr:'مصر',countryEn:'Egypt',code:'EG',lat:31.2001,lng:29.9187,timezone:'Africa/Cairo',method:'egypt'},
{id:'jo-amman',ar:'عمّان',en:'Amman',countryAr:'الأردن',countryEn:'Jordan',code:'JO',lat:31.9539,lng:35.9106,timezone:'Asia/Amman',method:'mwl'},
{id:'ps-jerusalem',ar:'القدس',en:'Jerusalem',countryAr:'فلسطين',countryEn:'Palestine',code:'PS',lat:31.7683,lng:35.2137,timezone:'Asia/Hebron',method:'mwl'},
{id:'sy-damascus',ar:'دمشق',en:'Damascus',countryAr:'سوريا',countryEn:'Syria',code:'SY',lat:33.5138,lng:36.2765,timezone:'Asia/Damascus',method:'mwl'},
{id:'lb-beirut',ar:'بيروت',en:'Beirut',countryAr:'لبنان',countryEn:'Lebanon',code:'LB',lat:33.8938,lng:35.5018,timezone:'Asia/Beirut',method:'mwl'},
{id:'iq-baghdad',ar:'بغداد',en:'Baghdad',countryAr:'العراق',countryEn:'Iraq',code:'IQ',lat:33.3152,lng:44.3661,timezone:'Asia/Baghdad',method:'mwl'},
{id:'ma-rabat',ar:'الرباط',en:'Rabat',countryAr:'المغرب',countryEn:'Morocco',code:'MA',lat:34.0209,lng:-6.8416,timezone:'Africa/Casablanca',method:'mwl'},
{id:'dz-algiers',ar:'الجزائر',en:'Algiers',countryAr:'الجزائر',countryEn:'Algeria',code:'DZ',lat:36.7538,lng:3.0588,timezone:'Africa/Algiers',method:'mwl'},
{id:'tn-tunis',ar:'تونس',en:'Tunis',countryAr:'تونس',countryEn:'Tunisia',code:'TN',lat:36.8065,lng:10.1815,timezone:'Africa/Tunis',method:'mwl'},
{id:'tr-istanbul',ar:'إسطنبول',en:'Istanbul',countryAr:'تركيا',countryEn:'Turkey',code:'TR',lat:41.0082,lng:28.9784,timezone:'Europe/Istanbul',method:'mwl'},
{id:'gb-london',ar:'لندن',en:'London',countryAr:'المملكة المتحدة',countryEn:'United Kingdom',code:'GB',lat:51.5074,lng:-0.1278,timezone:'Europe/London',method:'mwl'},
{id:'fr-paris',ar:'باريس',en:'Paris',countryAr:'فرنسا',countryEn:'France',code:'FR',lat:48.8566,lng:2.3522,timezone:'Europe/Paris',method:'mwl'},
{id:'de-berlin',ar:'برلين',en:'Berlin',countryAr:'ألمانيا',countryEn:'Germany',code:'DE',lat:52.52,lng:13.405,timezone:'Europe/Berlin',method:'mwl'},
{id:'us-new-york',ar:'نيويورك',en:'New York',countryAr:'الولايات المتحدة',countryEn:'United States',code:'US',lat:40.7128,lng:-74.006,timezone:'America/New_York',method:'north'},
{id:'ca-toronto',ar:'تورونتو',en:'Toronto',countryAr:'كندا',countryEn:'Canada',code:'CA',lat:43.6532,lng:-79.3832,timezone:'America/Toronto',method:'north'},
{id:'pk-karachi',ar:'كراتشي',en:'Karachi',countryAr:'باكستان',countryEn:'Pakistan',code:'PK',lat:24.8607,lng:67.0011,timezone:'Asia/Karachi',method:'karachi'},
{id:'my-kl',ar:'كوالالمبور',en:'Kuala Lumpur',countryAr:'ماليزيا',countryEn:'Malaysia',code:'MY',lat:3.139,lng:101.6869,timezone:'Asia/Kuala_Lumpur',method:'mwl'},
{id:'id-jakarta',ar:'جاكرتا',en:'Jakarta',countryAr:'إندونيسيا',countryEn:'Indonesia',code:'ID',lat:-6.2088,lng:106.8456,timezone:'Asia/Jakarta',method:'mwl'},
{id:'au-sydney',ar:'سيدني',en:'Sydney',countryAr:'أستراليا',countryEn:'Australia',code:'AU',lat:-33.8688,lng:151.2093,timezone:'Australia/Sydney',method:'mwl'}
];
