export type Hadith = {
  ar: string;
  en: string;
  source: string;
  narrator?: string;
};

export const hadiths: Hadith[] = [
  // ── الإيمان والأخلاق ──
  { ar: 'إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى.', en: 'Actions are judged by intentions, and each person will get what they intended.', source: 'صحيح البخاري 1، صحيح مسلم 1907', narrator: 'عمر بن الخطاب' },
  { ar: 'المسلم من سلم المسلمون من لسانه ويده.', en: 'A Muslim is one from whose tongue and hand other Muslims are safe.', source: 'صحيح البخاري 10، صحيح مسلم 40', narrator: 'عبد الله بن عمرو' },
  { ar: 'لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه.', en: 'None of you truly believes until he loves for his brother what he loves for himself.', source: 'صحيح البخاري 13، صحيح مسلم 45', narrator: 'أنس بن مالك' },
  { ar: 'من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت.', en: 'Whoever believes in Allah and the Last Day should speak good or remain silent.', source: 'صحيح البخاري 6018، صحيح مسلم 47', narrator: 'أبو هريرة' },
  { ar: 'الكلمة الطيبة صدقة.', en: 'A good word is charity.', source: 'صحيح البخاري 2989، صحيح مسلم 1009', narrator: 'أبو هريرة' },
  { ar: 'يسروا ولا تعسروا، وبشروا ولا تنفروا.', en: 'Make things easy and do not make them difficult. Give good tidings and do not drive people away.', source: 'صحيح البخاري 69، صحيح مسلم 1734', narrator: 'أنس بن مالك' },
  { ar: 'الدين النصيحة.', en: 'Religion is sincere counsel.', source: 'صحيح مسلم 55', narrator: 'تميم الداري' },
  { ar: 'لا تغضب.', en: 'Do not become angry.', source: 'صحيح البخاري 6116', narrator: 'أبو هريرة' },
  { ar: 'من لا يرحم لا يُرحم.', en: 'Whoever does not show mercy will not be shown mercy.', source: 'صحيح البخاري 6013، صحيح مسلم 2319', narrator: 'جرير بن عبد الله' },
  { ar: 'خيركم من تعلم القرآن وعلمه.', en: 'The best of you are those who learn the Quran and teach it.', source: 'صحيح البخاري 5027', narrator: 'عثمان بن عفان' },
  { ar: 'إن الله جميل يحب الجمال.', en: 'Allah is beautiful and loves beauty.', source: 'صحيح مسلم 91', narrator: 'عبد الله بن مسعود' },
  { ar: 'البر حسن الخلق.', en: 'Righteousness is good character.', source: 'صحيح مسلم 2553', narrator: 'النواس بن سمعان' },
  { ar: 'من غشنا فليس منا.', en: 'Whoever deceives us is not one of us.', source: 'صحيح مسلم 101', narrator: 'أبو هريرة' },
  { ar: 'الحياء من الإيمان.', en: 'Modesty is part of faith.', source: 'صحيح البخاري 24، صحيح مسلم 36', narrator: 'أبو هريرة' },
  { ar: 'المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف وفي كل خير.', en: 'The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.', source: 'صحيح مسلم 2664', narrator: 'أبو هريرة' },
  { ar: 'اتق الله حيثما كنت، وأتبع السيئة الحسنة تمحها، وخالق الناس بخلق حسن.', en: 'Fear Allah wherever you are, follow a bad deed with a good one and it will wipe it out, and treat people with good character.', source: 'صحيح الترمذي 1987', narrator: 'أبو ذر الغفاري' },
  { ar: 'لا يُلدغ المؤمن من جحر مرتين.', en: 'A believer is not stung from the same hole twice.', source: 'صحيح البخاري 6133، صحيح مسلم 2999', narrator: 'أبو هريرة' },
  { ar: 'لا تحاسدوا ولا تناجشوا ولا تباغضوا ولا تدابروا، وكونوا عباد الله إخواناً.', en: 'Do not envy one another, do not hate one another, do not turn your backs on one another. Rather, be servants of Allah as brothers.', source: 'صحيح مسلم 2563', narrator: 'أبو هريرة' },
  { ar: 'من سلك طريقاً يلتمس فيه علماً سهل الله له به طريقاً إلى الجنة.', en: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.', source: 'صحيح مسلم 2699', narrator: 'أبو هريرة' },
  { ar: 'تَبَسُّمُكَ في وجه أخيك صدقة.', en: 'Your smiling in the face of your brother is charity.', source: 'صحيح الترمذي 1956', narrator: 'أبو ذر الغفاري' },
  { ar: 'لا تحقرن من المعروف شيئاً ولو أن تلقى أخاك بوجه طلق.', en: 'Do not belittle any good deed, even meeting your brother with a cheerful face.', source: 'صحيح مسلم 2626', narrator: 'أبو ذر الغفاري' },
  { ar: 'المسلم أخو المسلم لا يظلمه ولا يسلمه، من كان في حاجة أخيه كان الله في حاجته.', en: 'A Muslim is the brother of a Muslim: he does not oppress him, nor does he fail him. Whoever fulfills the needs of his brother, Allah will fulfill his needs.', source: 'صحيح مسلم 2580', narrator: 'أبو هريرة' },
  { ar: 'آية المنافق ثلاث: إذا حدث كذب، وإذا وعد أخلف، وإذا اؤتمن خان.', en: 'The signs of a hypocrite are three: when he speaks he lies, when he makes a promise he breaks it, and when he is entrusted he betrays.', source: 'صحيح البخاري 33، صحيح مسلم 59', narrator: 'أبو هريرة' },
  { ar: 'لا يؤمن أحدكم حتى يكون هواه تبعاً لما جئت به.', en: 'None of you truly believes until his desires are subservient to what I have brought.', source: 'مستدرك الحاكم 1/93', narrator: 'عبد الله بن عمرو' },
  { ar: 'إن الله كتب الإحسان على كل شيء.', en: 'Allah has prescribed proficiency in all things.', source: 'صحيح مسلم 1955', narrator: 'شَدَّاد بن أوس' },
  { ar: 'أكمل المؤمنين إيماناً أحسنهم خلقاً.', en: 'The most complete of the believers in faith is the one with the best character.', source: 'سنن أبي داود 4682', narrator: 'أبو هريرة' },
  { ar: 'الطهور شطر الإيمان، والحمد لله تملأ الميزان، وسبحان الله والحمد لله تملآن ما بين السماوات والأرض.', en: 'Purification is half of faith. Alhamdulillah fills the scales, and SubhanAllah and Alhamdulillah fill what is between the heavens and the earth.', source: 'صحيح مسلم 223', narrator: 'أبو هريرة' },

  // ── الصلاة والعبادات ──
  { ar: 'إن أول ما يحاسب به العبد يوم القيامة من عمله صلاته، فإن صلحت فقد أفلح وأنجح، وإن فسدت فقد خاب وخسر.', en: 'The first thing for which a person will be brought to account on the Day of Resurrection will be his prayer. If it is sound, he will be successful; if it is bad, he will be doomed.', source: 'صحيح النسائي 465، سنن الترمذي 413', narrator: 'تميم الداري' },
  { ar: 'بين الرجل وبين الكفر والشرك ترك الصلاة.', en: 'Between a man and polytheism and disbelief is the abandonment of prayer.', source: 'صحيح مسلم 82', narrator: 'جابر بن عبد الله' },
  { ar: 'صلِّ كما رأيتني أصلي.', en: 'Pray as you have seen me praying.', source: 'صحيح البخاري 631', narrator: 'مالك بن الحويرث' },
  { ar: 'جعلت لي الأرض مسجداً وطهوراً.', en: 'The earth has been made for me a place of prostration and a means of purification.', source: 'صحيح البخاري 335، صحيح مسلم 521', narrator: 'أبو هريرة' },
  { ar: 'أفضل الأعمال الصلاة على وقتها.', en: 'The best of deeds is prayer at its appointed time.', source: 'صحيح البخاري 527، صحيح مسلم 625', narrator: 'عبد الله بن مسعود' },
  { ar: 'من صلى العشاء في جماعة فكأنما قام نصف الليل، ومن صلى الصبح في جماعة فكأنما صلى الليل كله.', en: 'Whoever prays Isha in congregation is as if he stood in prayer for half the night. Whoever prays Fajr in congregation is as if he stood in prayer the whole night.', source: 'صحيح مسلم 656', narrator: 'عثمان بن عفان' },
  { ar: 'من صلى لله أربعين يوماً في جماعة يدرك التكبيرة الأولى كُتبت له براءة من النار وبراءة من النفاق.', en: 'Whoever prays forty days in congregation, catching the first takbeer, will be granted two immunities: immunity from the Fire and immunity from hypocrisy.', source: 'سنن الترمذي 241', narrator: 'أنس بن مالك' },
  { ar: 'أقرب ما يكون العبد من ربه وهو ساجد فأكثروا الدعاء.', en: 'The closest a servant is to his Lord is when he is prostrating, so increase your supplications.', source: 'صحيح مسلم 482', narrator: 'أبو هريرة' },
  { ar: 'صلاة الجماعة تفضل صلاة الفذ بسبع وعشرين درجة.', en: 'Congregational prayer is twenty-seven times better than praying alone.', source: 'صحيح البخاري 645، صحيح مسلم 650', narrator: 'عبد الله بن عمر' },
  { ar: 'إن المسجد إذا سُبق إليه رجل فليجلس حيث انتهى به المجلس.', en: 'If someone arrives early at the mosque, let him sit wherever the gathering ends.', source: 'سنن أبي داود 673', narrator: 'جابر بن عبد الله' },

  // ── القرآن ──
  { ar: 'اقرؤوا القرآن فإنه يأتي يوم القيامة شفيعاً لأصحابه.', en: 'Read the Quran, for it will come on the Day of Resurrection as an intercessor for its companions.', source: 'صحيح مسلم 804', narrator: 'أبو أمامة الباهلي' },
  { ar: 'الماهر بالقرآن مع السفرة الكرام البررة، والذي يقرأ القرآن ويتتعتع فيه وهو عليه شاق له أجران.', en: 'The one who is proficient in the Quran will be with the honorable and obedient scribes. The one who reads it and struggles with it will have two rewards.', source: 'صحيح البخاري 4937، صحيح مسلم 798', narrator: 'عائشة بنت أبي بكر' },
  { ar: 'لا حسد إلا في اثنتين: رجل آتاه الله القرآن فهو يقوم به آناء الليل وآناء النهار، ورجل آتاه الله مالاً فهو ينفقه آناء الليل وآناء النهار.', en: 'There is no envy except in two cases: a man whom Allah has given the Quran and he recites it night and day, and a man whom Allah has given wealth and he spends it night and day.', source: 'صحيح البخاري 7527', narrator: 'عبد الله بن عمر' },
  { ar: 'من قرأ حرفاً من كتاب الله فله به حسنة، والحسنة بعشر أمثالها، لا أقول الم حرف ولكن ألف حرف ولام حرف وميم حرف.', en: 'Whoever reads a letter from the Book of Allah will have a reward, and that reward will be multiplied by ten. I do not say that Alif-Laam-Meem is a letter, rather Alif is a letter, Laam is a letter and Meem is a letter.', source: 'سنن الترمذي 2910', narrator: 'عبد الله بن مسعود' },
  { ar: 'خيركم من تعلم القرآن وعلمه.', en: 'The best of you are those who learn the Quran and teach it.', source: 'صحيح البخاري 5027', narrator: 'عثمان بن عفان' },
  { ar: 'لا تقوم الساعة حتى يُقبض العلم وتكثر الزلازل ويتقارب الزمان وتظهر الفتن ويكثر الهرج وهو القتل.', en: 'The Hour will not be established until knowledge is taken away, earthquakes increase, time passes quickly, tribulations appear, and there is much bloodshed.', source: 'صحيح البخاري 1036', narrator: 'أبو هريرة' },

  // ── الدعاء والذكر ──
  { ar: 'الدعاء هو العبادة.', en: 'Supplication is the essence of worship.', source: 'صحيح الترمذي 3370', narrator: 'النعمان بن بشير' },
  { ar: 'ادعوا الله وأنتم موقنون بالإجابة، واعلموا أن الله لا يستجيب دعاءً من قلب غافل لاهٍ.', en: 'Call upon Allah while being certain of being answered. Know that Allah does not respond to a supplication from a heedless and distracted heart.', source: 'صحيح الترمذي 3479', narrator: 'أبو هريرة' },
  { ar: 'مَثل الذي يذكر ربه والذي لا يذكر ربه مثل الحي والميت.', en: 'The comparison of one who remembers Allah and one who does not, is like the comparison between the living and the dead.', source: 'صحيح البخاري 6407، صحيح مسلم 779', narrator: 'أبو موسى الأشعري' },
  { ar: 'أحب الأعمال إلى الله أدومها وإن قل.', en: 'The most beloved of deeds to Allah are those that are most consistent, even if they are small.', source: 'صحيح البخاري 6464، صحيح مسلم 782', narrator: 'عائشة بنت أبي بكر' },
  { ar: 'إن الله لا يمل حتى تملوا.', en: 'Allah does not get tired of giving rewards until you get tired of doing good deeds.', source: 'صحيح البخاري 7405، صحيح مسلم 2819', narrator: 'أبو هريرة' },
  { ar: 'من لزم الاستغفار جعل الله له من كل هم فرجاً ومن كل ضيق مخرجاً ورزقه من حيث لا يحتسب.', en: 'Whoever persists in seeking forgiveness, Allah will appoint for him a way out of every distress, and relief from every anxiety, and will provide for him from where he did not reckon.', source: 'سنن أبي داود 1518', narrator: 'عبد الله بن عباس' },
  { ar: 'الدعاء لا يُرد ما دام يدعو.', en: 'A supplication is never rejected as long as the person keeps supplicating.', source: 'صحيح الترمذي 3604', narrator: 'أبو هريرة' },
  { ar: 'من لم يسأل الله يغضب عليه.', en: 'Whoever does not ask Allah, He becomes angry with him.', source: 'سنن الترمذي 3373', narrator: 'أبو هريرة' },
  { ar: 'استgartوا ربكم تُستجابوا.', en: 'Ask your Lord, and He will answer you.', source: 'صحيح الترمذي 3573', narrator: 'أنس بن مالك' },
  { ar: 'ألظوا بيا ذا الجلال والإكرام.', en: 'Persist in saying: O Possessor of Majesty and Generosity.', source: 'سنن الترمذي 3544', narrator: 'ربيعة بن كعب' },
  { ar: 'سيد الاستغفار أن يقول العبد: اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك علي، وأبوء بذنبي فاغفر لي فإنه لا يغفر الذنوب إلا أنت.', en: 'The best supplication for forgiveness is to say: O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your slave. I am faithful to my covenant and my promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge before You Your favor upon me, and I acknowledge my sins. So forgive me, for there is none who can forgive sins except You.', source: 'صحيح البخاري 6307', narrator: 'شَدَّاد بن أوس' },

  // ── الصبر والابتلاء ──
  { ar: 'عجباً لأمر المؤمن إن أمره كله خير، إن أصابته سراء شكر فكان خيراً له، وإن أصابته ضراء صبر فكان خيراً له.', en: 'How wonderful is the affair of the believer, for his affair is all good. If something good happens to him, he is grateful for it and that is good for him. If something bad happens to him, he bears it with patience and that is good for him.', source: 'صحيح مسلم 2999', narrator: 'صهيب بن سنان' },
  { ar: 'إنما يُوَفَّى الصابرون أجرهم بغير حساب.', en: 'Indeed, the patient will be given their reward without account.', source: 'صحيح البخاري 2400', narrator: 'أنس بن مالك' },
  { ar: 'ما يصيب المؤمن من نصب ولا وصب ولا هم ولا حزن حتى الهم يهمه إلا كفّر الله بها من خطاياه.', en: 'No fatigue, illness, anxiety, sorrow, harm, or distress afflicts a Muslim, even the prick of a thorn, but Allah expiates some of his sins thereby.', source: 'صحيح البخاري 5641، صحيح مسلم 2573', narrator: 'أبو سعيد الخدري وأبو هريرة' },
  { ar: 'ومن يتوكل على الله فهو حسبه.', en: 'And whoever relies upon Allah — then He is sufficient for him.', source: 'سنن الترمذي 2344', narrator: 'عمر بن الخطاب' },
  { ar: 'إذا أصاب أحدكم هم فليسترجع: اللهم إني عبدك وابن عبدك وابن أمتك، ناصيتي بيدك، ماضٍ فيّ حكمك، عدل فيّ قضاؤك، أسألك بكل اسم هو لك سميت به نفسك أو أنزلته في كتابك أو علمته أحداً من خلقك أو استأثرت به في علم الغيب عندك أن تجعل القرآن ربيع قلبي ونور صدري وجلاء حزني وذهاب همي.', en: 'When distress befalls someone, let him say: O Allah, I am Your slave, son of Your slave, son of Your female slave. My forelock is in Your hand. Your command over me is forever executed and Your decree over me is just. I ask You by every name belonging to You which You named Yourself with, or revealed in Your Book, or You taught to any of Your creation, or You have preserved in the knowledge of the unseen with You, that You make the Quran the life of my heart and the light of my breast, and a departure for my sorrow and a release for my anxiety.', source: 'سنن أحمد 1/391', narrator: 'عبد الله بن مسعود' },
  { ar: 'لا يُكلف الله نفساً إلا وسعها.', en: 'Allah does not burden a soul beyond that it can bear.', source: 'سورة البقرة 286 (قرآن كريم)', narrator: '' },
  { ar: 'إن مع العسر يسراً، إن مع العسر يسراً.', en: 'Indeed, with hardship comes ease. Indeed, with hardship comes ease.', source: 'سورة الشرح 5-6 (قرآن كريم)', narrator: '' },

  // ── العلم والتعلّم ──
  { ar: 'من يرد الله به خيراً يُفَقِّهه في الدين.', en: 'When Allah wishes good for someone, He grants him understanding of the religion.', source: 'صحيح البخاري 71، صحيح مسلم 1037', narrator: 'معاوية بن أبي سفيان' },
  { ar: 'طلب العلم فريضة على كل مسلم.', en: 'Seeking knowledge is an obligation upon every Muslim.', source: 'سنن ابن ماجه 224', narrator: 'أنس بن مالك' },
  { ar: 'من سلك طريقاً يلتمس فيه علماً سهل الله له طريقاً إلى الجنة.', en: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.', source: 'صحيح مسلم 2699', narrator: 'أبو هريرة' },
  { ar: 'إذا مات الإنسان انقطع عمله إلا من ثلاث: صدقة جارية، أو علم يُنتفع به، أو ولد صالح يدعو له.', en: 'When a person dies, all his deeds end except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.', source: 'صحيح مسلم 1631', narrator: 'أبو هريرة' },
  { ar: 'من خرج في طلب العلم فهو في سبيل الله حتى يرجع.', en: 'Whoever goes out seeking knowledge is in the path of Allah until he returns.', source: 'سنن الترمذي 2647', narrator: 'أنس بن مالك' },
  { ar: 'لا ضرر ولا ضرار.', en: 'There should be neither harming nor reciprocating harm.', source: 'سنن ابن ماجه 2340', narrator: 'عبادة بن الصامت' },

  // ── الجنة والنار ──
  { ar: 'حُفَّت الجنة بالمكاره وحُفَّت النار بالشهوات.', en: 'Paradise is surrounded by hardships and the Hellfire is surrounded by desires.', source: 'صحيح مسلم 2822', narrator: 'أبو هريرة' },
  { ar: 'إن أهل الجنة ليتراءون أهل الغرف من فوقهم كما يتراءون الكوكب الدري الغابر في الأفق من المشرق أو المغرب لتفاضل ما بينهم.', en: 'The people of Paradise will look at the people of the upper chambers above them as one looks at a shining star in the sky.', source: 'صحيح البخاري 3250، صحيح مسلم 2831', narrator: 'أبو سعيد الخدري' },
  { ar: 'من خاف أدلج، ومن أدلج بلغ المنزل، ألا إن سلعة الله غالية، ألا إن سلعة الله الجنة.', en: 'Whoever fears sets out at nightfall, and whoever sets out at nightfall reaches his destination. Indeed, the commodity of Allah is precious. Indeed, the commodity of Allah is Paradise.', source: 'صحيح الترمذي 2450', narrator: 'أبو هريرة' },
  { ar: 'لَصَلاةُ الجماعةِ أفضلُ من صلاةِ الفَذِّ بسَبعٍ وعِشرينَ درجةً.', en: 'The prayer in congregation is twenty-seven times better than the prayer offered individually.', source: 'صحيح البخاري 645', narrator: 'عبد الله بن عمر' },
  { ar: 'إن في الجنة سوقاً يأتونها كل جمعة، فتهب ريح الشمال فتحثّ في وجوههم وثيابهم فيزدادون حسناً وجمالاً.', en: 'There is a market in Paradise to which the people come every Friday. The north wind will blow and scatter fragrance in their faces and clothes, and they will increase in beauty and handsomeness.', source: 'صحيح مسلم 2833', narrator: 'علي بن أبي طالب' },
  { ar: 'إن أهون أهل النار عذاباً من له نعلان من نار يغلي منهما دماغه، يرى أنه أشد أهل النار عذاباً وإنه أهونهم عذاباً.', en: 'The person with the least punishment in Hell will be wearing two sandals of fire that will cause his brain to boil. He will think he is the most severely punished, even though he is the least punished.', source: 'صحيح البخاري 6562، صحيح مسلم 213', narrator: 'النعمان بن بشير' },

  // ── الصدقة والمعاملة ──
  { ar: 'الصدقة برهان.', en: 'Charity is a proof.', source: 'صحيح مسلم 223', narrator: 'أبو هريرة' },
  { ar: 'ما نقصت صدقة من مال.', en: 'Charity does not decrease wealth.', source: 'صحيح مسلم 2588', narrator: 'أبو هريرة' },
  { ar: 'سبعة يظلهم الله في ظله يوم لا ظل إلا ظله: إمام عادل، وشاب نشأ في عبادة الله، ورجل قلبه معلق في المساجد، ورجلان تحابا في الله اجتمعا عليه وتفرقا عليه، ورجل دعته امرأة ذات منصب وجمال فقال إني أخاف الله، ورجل تصدق بصدقة فأخفاها حتى لا تعلم شماله ما تنفق يمينه، ورجل ذكر الله خالياً ففاضت عيناه.', en: 'Seven will be shaded by Allah on the Day when there will be no shade but His: a just ruler, a young man who grew up worshipping Allah, a man whose heart is attached to the mosques, two men who love each other for Allah, a man who is called by a woman of beauty and position but says I fear Allah, a man who gives charity so secretly that his left hand does not know what his right hand gives, and a man who remembers Allah in private and his eyes overflow with tears.', source: 'صحيح البخاري 660، صحيح مسلم 1031', narrator: 'أبو هريرة' },
  { ar: 'يا غلام إني أعلمك كلمات: احفظ الله يحفظك، احفظ الله تجده تجاهك، إذا سألت فاسأل الله، وإذا استعنت فاستعن بالله، واعلم أن الأمة لو اجتمعت على أن ينفعوك بشيء لم ينفعوك إلا بشيء قد كتبه الله لك، ولو اجتمعوا على أن يضروك بشيء لم يضروك إلا بشيء قد كتبه الله عليك، رُفعت الأقلام وجفت الصحف.', en: 'O young man, I will teach you some words: Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him before you. If you ask, ask Allah; if you seek help, seek help from Allah. Know that if the entire nation were to gather together to benefit you, they would only benefit you with what Allah has already written for you, and if they were to gather to harm you, they would only harm you with what Allah has already written against you. The pens have been lifted and the pages have dried.', source: 'سنن الترمذي 2516', narrator: 'عبد الله بن عباس' },
  { ar: 'من كان يؤمن بالله واليوم الآخر فليكرم ضيفه.', en: 'Whoever believes in Allah and the Last Day should honor his guest.', source: 'صحيح البخاري 6018', narrator: 'أبو هريرة' },
  { ar: 'من كان يؤمن بالله واليوم الآخر فليصل رحمه.', en: 'Whoever believes in Allah and the Last Day should maintain the ties of kinship.', source: 'صحيح البخاري 5787', narrator: 'أبو هريرة' },
  { ar: 'كل سُلامى من الناس عليه صدقة، كل يوم تطلع فيه الشمس: تعدل بين الاثنين صدقة، وتعين الرجل في دابته فتحمله عليها أو ترفع له عليها متاعه صدقة، والكلمة الطيبة صدقة، وبكل خطوة تمشيها إلى الصلاة صدقة، وتميط الأذى عن الطريق صدقة.', en: 'Every joint of a person must perform a charity every day the sun rises: settling a dispute between two people is charity, helping a man with his mount is charity, lifting his luggage onto it is charity, a good word is charity, every step you take towards prayer is charity, and removing harmful things from the road is charity.', source: 'صحيح البخاري 2989، صحيح مسلم 1009', narrator: 'أبو هريرة' },
  { ar: 'اتقوا النار ولو بشق تمرة.', en: 'Protect yourselves from the Fire even with half a date.', source: 'صحيح البخاري 1417، صحيح مسلم 1016', narrator: 'عدي بن حاتم' },

  // ── الصيام والعبادات الأخرى ──
  { ar: 'من صام رمضان إيماناً واحتساباً غُفر له ما تقدم من ذنبه.', en: 'Whoever fasts Ramadan out of faith and seeking reward, his previous sins will be forgiven.', source: 'صحيح البخاري 38، صحيح مسلم 760', narrator: 'أبو هريرة' },
  { ar: 'الصيام جُنّة، فإذا كان يوم صوم أحدكم فلا يرفث ولا يصخب، فإن سابّه أحد أو قاتله فليقل إني صائم.', en: 'Fasting is a shield. So the fasting person should avoid obscene speech and should not behave foolishly, and if somebody fights with him or insults him, he should say: I am fasting.', source: 'صحيح البخاري 1894، صحيح مسلم 1151', narrator: 'أبو هريرة' },
  { ar: 'من قام رمضان إيماناً واحتساباً غُفر له ما تقدم من ذنبه.', en: 'Whoever stands in prayer on the Night of Decree out of faith and seeking reward, his previous sins will be forgiven.', source: 'صحيح البخاري 1901، صحيح مسلم 760', narrator: 'أبو هريرة' },
  { ar: 'العمرة إلى العمرة كفارة لما بينهما، والحج المبرور ليس له جزاء إلا الجنة.', en: 'Umrah to Umrah is expiation for what comes between them, and the accepted Hajj has no reward other than Paradise.', source: 'صحيح البخاري 1773، صحيح مسلم 1349', narrator: 'أبو هريرة' },
  { ar: 'إنما بُعثت لأتمم مكارم الأخلاق.', en: 'I was sent to perfect good character.', source: 'سنن البيهقي 2/200', narrator: 'أبو هريرة' },
  { ar: 'خصلتان لا يحافظ عليهما عبد مسلم إلا دخل الجنة، هما سنتان رخيصتان: سبحة بعد كل صلاة، وركعتان قبل الفجر.', en: 'There are two qualities that no Muslim preserves except that he will enter Paradise: two rak'ahs before Fajr prayer, and glorifying Allah after every obligatory prayer.', source: 'صحيح الترمذي 471', narrator: 'أبو هريرة' },

  // ── التوبة والاستغفار ──
  { ar: 'إن الله يبسط يده بالليل ليتوب مسيء النهار، ويبسط يده بالنهار ليتوب مسيء الليل.', en: 'Allah extends His hand at night to accept the repentance of the one who sinned during the day, and He extends His hand during the day to accept the repentance of the one who sinned at night.', source: 'صحيح مسلم 2759', narrator: 'أبو موسى الأشعري' },
  { ar: 'إن الله كتب الحسنات والسيئات... فمن هم بحسنة فلم يعملها كتبها الله عنده حسنة كاملة، وإن هم بها فعملها كتبها الله عنده عشر حسنات... وإن هم بسيئة فلم يعملها كتبها الله عنده حسنة كاملة.', en: 'Allah has recorded good and evil deeds... Whoever intends to do a good deed but does not do it, Allah records it as a complete good deed. If he intends and does it, Allah records it as ten good deeds... If he intends to do an evil deed but does not do it, Allah records it as a complete good deed.', source: 'صحيح البخاري 6491، صحيح مسلم 131', narrator: 'عبد الله بن عباس' },
  { ar: 'يا ابن آدم لو بلغت ذنوبك عنان السماء ثم استغفرتني غفرت لك ولا أبالي، يا ابن آدم إنك لو أتيتني بقراب الأرض خطايا ثم لقيتني لا تشرك بي شيئاً لأتيتك بقرابها مغفرة.', en: 'O son of Adam, were your sins to reach the clouds of the sky and were you then to ask forgiveness of Me, I would forgive you. O son of Adam, were you to come to Me with sins nearly as great as the earth and were you then to face Me, ascribing no partner to Me, I would bring you forgiveness nearly as great as it.', source: 'سنن الترمذي 3540', narrator: 'أنس بن مالك' },
  { ar: 'التائب من الذنب كمن لا ذنب له.', en: 'The one who repents from a sin is like one who has no sin.', source: 'سنن ابن ماجه 4250', narrator: 'عبد الله بن مسعود' },

  // ── التراحم والتعامل مع الناس ──
  { ar: 'من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت، ومن كان يؤمن بالله واليوم الآخر فليكرم جاره، ومن كان يؤمن بالله واليوم الآخر فليكرم ضيفه.', en: 'Whoever believes in Allah and the Last Day should speak good or remain silent, should honor his neighbor, and should honor his guest.', source: 'صحيح البخاري 6018، صحيح مسلم 47', narrator: 'أبو هريرة' },
  { ar: 'لا تدخلوا الجنة حتى تؤمنوا ولا تؤمنوا حتى تحابوا، أولا أدلكم على شيء إذا فعلتموه تحاببتم: أفشوا السلام بينكم.', en: 'You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I not tell you about something which, if you do it, you will love one another? Spread the greeting of peace among yourselves.', source: 'صحيح مسلم 54', narrator: 'أبو هريرة' },
  { ar: 'المؤمن للمؤمن كالبنيان يشد بعضه بعضاً.', en: 'The believer to the believer is like a solid building, one part supporting the other.', source: 'صحيح البخاري 6026، صحيح مسلم 2585', narrator: 'أبو هريرة' },
  { ar: 'مَثَلُ المؤمنين في توادهم وتعاطفهم وتراحمهم مثل الجسد، إذا اشتكى منه عضو تداعى له سائر الجسد بالسهر والحمى.', en: 'The believers in their mutual kindness, compassion, and sympathy are just like one body. When one of the limbs suffers, the whole body responds to it with wakefulness and fever.', source: 'صحيح مسلم 2586', narrator: 'النعمان بن بشير' },
  { ar: 'لا تحاسدوا ولا تناجشوا ولا تباغضوا ولا تدابروا، وكونوا عباد الله إخواناً. المسلم أخو المسلم لا يظلمه ولا يُسلمه.', en: 'Do not envy one another, do not hate one another, do not turn your backs on one another. Be servants of Allah as brothers. A Muslim is the brother of a Muslim; he does not oppress him or fail him.', source: 'صحيح مسلم 2563', narrator: 'أبو هريرة' },
  { ar: 'ليس منا من لم يرحم صغيرنا ويوقّر كبيرنا.', en: 'He is not one of us who does not show mercy to our young and does not respect our old.', source: 'سنن الترمذي 1919', narrator: 'أنس بن مالك' },
  { ar: 'إياكم والظن فإن الظن أكذب الحديث، ولا تجسسوا ولا تحسسوا ولا تنافسوا ولا تحاسدوا ولا تباغضوا وكونوا عباد الله إخواناً.', en: 'Beware of suspicion, for suspicion is the worst of false tales. Do not spy, do not envy one another, do not hate one another, do not turn away from one another. Be servants of Allah as brothers.', source: 'صحيح البخاري 6066، صحيح مسلم 2563', narrator: 'أبو هريرة' },

  // ── فضائل الأعمال ──
  { ar: 'إن في الجنة غرفاً يرى ظاهرها من باطنها وباطنها من ظاهرها، أعدها الله لمن أطعم الطعام وأفشى السلام وصلى بالليل والناس نيام.', en: 'In Paradise there are rooms whose outside can be seen from inside and inside from outside. Allah has prepared them for those who feed others, spread the greeting of peace, and pray at night while people are sleeping.', source: 'سنن ابن ماجه 1330', narrator: 'علي بن أبي طالب' },
  { ar: 'حُفت الجنة بالمكاره وحُفت النار بالشهوات.', en: 'Paradise is surrounded by hardships and the Hellfire is surrounded by desires.', source: 'صحيح مسلم 2822', narrator: 'أبو هريرة' },
  { ar: 'من قام ليلة القدر إيماناً واحتساباً غفر له ما تقدم من ذنبه.', en: 'Whoever stands in prayer on the Night of Decree out of faith and seeking reward, his previous sins will be forgiven.', source: 'صحيح البخاري 1901', narrator: 'أبو هريرة' },
  { ar: 'إن للمسلم على أخيه ستاً بالمعروف: يسلم عليه إذا لقيه، ويشمته إذا عطس، ويجيبه إذا دعاه، ويشهده إذا مات، ويعوده إذا مرض، ويتبع جنازته إذا مات.', en: 'A Muslim has six rights over another Muslim: greet him when you meet him, respond to his sneeze, accept his invitation, visit him when he is sick, follow his funeral, and respond to his greeting.', source: 'صحيح مسلم 2162', narrator: 'أبو هريرة' },
  { ar: 'الطهور شطر الإيمان، والحمد لله تملأ الميزان، وسبحان الله والحمد لله تملآن أو تملأ ما بين السماوات والأرض.', en: 'Purification is half of faith, and Alhamdulillah fills the scales, and SubhanAllah and Alhamdulillah fill what is between the heavens and the earth.', source: 'صحيح مسلم 223', narrator: 'أبو هريرة' },
];
